### ISSUE TITLE
DCC Get Command?

### ISSUE THREAD

**Issue by IshanArya** [Booster2ooo/irc-xdcc#3]
If I CTCP send from a bot on the IRC channel, is there any way to run the /dcc get command to accept the file? If not, can this be implemented?

**Comment by Booster2ooo** [comment]
I'm not a hundred percent sure but you could try by [changing the method and sendCommand options](https://github.com/Booster2ooo/irc-xdcc#options) --> method to 'dcc' and sendCommand to 'get' or just sendCommand to 'dcc get'.

If you have more pieces of information about the process (raw commandes, expected replies, etc.) I could have a look into it.

**Comment by IshanArya** [comment]
Thanks for your help. Somehow, XDCC automatically added the file to the pool, and it worked.

**Comment by Booster2ooo** [comment]
When acceptUnpooled is set to true, any CTCP DCC message will be [parsed using the internal regexp _dccParser](https://github.com/Booster2ooo/irc-xdcc/blob/master/lib/irc-xdcc.js#L167) (/DCC (\w+) "?'?(.+?)'?"? (\d+) (\d+) ?(\d+)?/) and automatically added to the pool. I'm glad to know this feature has been useful to you.
